site_name: 'AO Physics'
nav:
  - Getting Started: 
    - Overview: 'index.md'
    - Setup: 'setup.md'
  - Classes: 
    - World: 'world.md'
    - Body: 'body.md'
    - Constraint: 'constraint.md'
    - Character: 'character.md'
  - Examples:
    - 'examples/basic.md'
  - Other:
    - 'lua_module.md'

markdown_extensions:
- admonition

theme: 
  name: readthedocs
  logo: 'img/AOP.png'
  user_color_mode_toggle: true
  nav_style: dark
  # highlightjs: true
  color_mode: dark

plugins:
# - search:

extra_javascript:
  - assets/linenumbers.js

extra_css:
  - assets/style.css
  - assets/vscode.css