site_name: AO Physics (AOP)
nav:
  - AOP: 'index.md'
  - World: 'world.md'
  - Body: 'body.md'
  - Constraint: 'constraint.md'


theme: 
  name: mkdocs
  user_color_mode_toggle: true
  nav_style: dark
  highlightjs: true
  color_mode: dark
