site_name: AO Physics (AOP)
nav:
  - 'AO Physics': 'index.md'
  - Getting Started: 
    - Setup: 'setup.md'
  - Classes: 
    - World: 'world.md'
    - Body: 'body.md'
    - Constraint: 'constraint.md'
    - Character: 'character.md'
  - Examples:
    - 'examples/basic.md'
  - Other:
    - 'lua_module.md'

markdown_extensions:
  - admonition

theme: 
  name: readthedocs
  user_color_mode_toggle: true
  nav_style: dark
  highlightjs: true
  color_mode: dark
