site_name: AO Physics (AOP)
nav:
  - Overview: 'index.md'
  - Classes: 
    - World: 'world.md'
    - Body: 'body.md'
    - Constraint: 'constraint.md'
  - Examples:
    - 'examples/basic.md'


theme: 
  name: mkdocs
  user_color_mode_toggle: true
  nav_style: dark
  highlightjs: true
  color_mode: dark
